defmodule ContactCrudBackEnd.Repo.Migrations.PhotoHashAttribute do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:contacts) do
      add :photo_hash, :text
    end
  end

  def down do
    alter table(:contacts) do
      remove :photo_hash
    end
  end
end
