defmodule ContactCrudBackEnd.Repo.Migrations.ContactResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:contacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :phone, :text, null: false
      add :email, :text, null: false
      add :company, :text, null: false
    end

    create unique_index(:contacts, [:email], name: "contacts_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:contacts, [:email], name: "contacts_unique_email_index")

    drop table(:contacts)
  end
end
