defmodule ContactCrudBackEnd.Repo.Migrations.ChangedPhotoHashDefault do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:contacts) do
      modify :photo_hash, :text, default: nil
    end
  end

  def down do
    alter table(:contacts) do
      modify :photo_hash, :text, default: ""
    end
  end
end
